spring:
  kafka:
    bootstrap-servers: 43.200.43.104:9092
    producer:
      # ???? key ??? ?? : ?? ??? ???(String)? ???? Kafka? ??
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # ???? value ??? ?? : ?? ??? ???(String)? ???? Kafka? ??
      value-serializer: org.apache.kafka.common.serialization.StringSerializer